// Code generated by protoc-gen-quix-errors. DO NOT EDIT.
// source: {{.SourcePath}}

package {{.PackageName}}

import qerrors "{{qerrorsPkg}}"

const (
{{- range .Enum.Values}}
	{{.ConstName}} = "{{.Code}}"
{{- end}}
)
{{range .Enum.Values}}
{{- if not .IsUnspecified}}
// {{.FuncName}} returns an Error with code "{{.Code}}", message "{{.Message}}", HTTP status {{.HTTPStatus}}.
func {{.FuncName}}() *qerrors.Error {
	return &qerrors.Error{
		Code:       {{.ConstName}},
		Message:    {{printf "%q" .Message}},
		StatusCode: {{.HTTPStatus}},
	}
}

// {{.FuncNameWD}} returns an Error with code "{{.Code}}", message "{{.Message}}", HTTP status {{.HTTPStatus}}, and the given details.
func {{.FuncNameWD}}(details any) *qerrors.Error {
	return &qerrors.Error{
		Code:       {{.ConstName}},
		Message:    {{printf "%q" .Message}},
		StatusCode: {{.HTTPStatus}},
		Details:    details,
	}
}
{{- end}}
{{end}}
