// Code generated by protoc-gen-quix-gin. DO NOT EDIT.
// source: {{.SourcePath}}

package {{.PackageName}}

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
	"{{runtimePkg}}"
	{{- range .ExtraImports}}
	"{{.}}"
	{{- end}}
)

{{range $svc := .Services}}
// {{$svc.InterfaceName}} is the HTTP service interface for {{$svc.GoName}}.
type {{$svc.InterfaceName}} interface {
	{{- range $svc.Methods}}
	{{.GoName}}(context.Context, {{.InputType}}) ({{if .IsVoidReturn}}error{{else}}{{.OutputType}}, error{{end}})
	{{- end}}
}

// {{$svc.RegisterFuncName}} registers HTTP handlers for {{$svc.GoName}} onto the given router group.
func {{$svc.RegisterFuncName}}(g *gin.RouterGroup, svc {{$svc.InterfaceName}}) {
	r := g.Group("")
	{{- range $method := $svc.Methods}}
	{{- range $mi, $route := $method.Routes}}
	r.{{$route.Method}}("{{$route.Path}}", _{{$svc.GoName}}_{{$method.GoName}}{{$mi}}_HTTP_Handler(svc))
	{{- end}}
	{{- end}}
}

{{range $mi, $method := $svc.Methods}}
{{range $ri, $route := $method.Routes}}
func _{{$svc.GoName}}_{{$method.GoName}}{{$ri}}_HTTP_Handler(svc {{$svc.InterfaceName}}) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		c := &runtime.Context{Context: ctx}
		shouldBind := func(req {{$method.InputType}}) error {
			{{- if and $route.HasBody (eq $route.BodyField "*")}}
			if err := c.ShouldBindJSON(req); err != nil {
				return err
			}
			{{- end}}
			{{- if and $route.HasBody (ne $route.BodyField "*")}}
			if err := c.ShouldBindQuery(req); err != nil {
				return err
			}
			if err := c.ShouldBindUri(req); err != nil {
				return err
			}
			// Bind body to nested field
			if err := c.ShouldBindJSON(req.{{exportField $route.BodyField}}); err != nil {
				return err
			}
			{{- end}}
			{{- if not $route.HasBody}}
			if err := c.ShouldBindQuery(req); err != nil {
				return err
			}
			if err := c.ShouldBindUri(req); err != nil {
				return err
			}
			{{- end}}
			return nil
		}
		var err error
		req := new({{trimPrefix $method.InputType "*"}})
		{{- if not $method.IsVoidReturn}}
		var rsp {{$method.OutputType}}
		{{- end}}
		if err = shouldBind(req); err != nil {
			c.SetError(err)
			return
		}
		{{- if not $method.IsVoidReturn}}
		rsp, err = svc.{{$method.GoName}}(c.Request.Context(), req)
		{{- else}}
		_, err = svc.{{$method.GoName}}(c.Request.Context(), req)
		{{- end}}
		if err != nil {
			c.SetError(err)
			return
		}
		{{- if not $method.IsVoidReturn}}
		if c.ContentType() == "application/x-protobuf" {
			c.ProtoBuf(http.StatusOK, rsp)
		} else {
			c.JSON(http.StatusOK, rsp)
		}
		{{- else}}
		c.Status(http.StatusNoContent)
		{{- end}}
	}
}
{{end}}
{{end}}
{{end}}
