// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: errdesc/errdesc.proto

package errdesc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_errdesc_errdesc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         84001,
		Name:          "errdesc.http_status",
		Tag:           "varint,84001,opt,name=http_status",
		Filename:      "errdesc/errdesc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         84002,
		Name:          "errdesc.error_message",
		Tag:           "bytes,84002,opt,name=error_message",
		Filename:      "errdesc/errdesc.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// http_status maps an enum value to an HTTP status code.
	//
	// optional int32 http_status = 84001;
	E_HttpStatus = &file_errdesc_errdesc_proto_extTypes[0]
	// error_message provides a human-readable error message for the enum value.
	//
	// optional string error_message = 84002;
	E_ErrorMessage = &file_errdesc_errdesc_proto_extTypes[1]
)

var File_errdesc_errdesc_proto protoreflect.FileDescriptor

const file_errdesc_errdesc_proto_rawDesc = "" +
	"\n" +
	"\x15errdesc/errdesc.proto\x12\aerrdesc\x1a google/protobuf/descriptor.proto:D\n" +
	"\vhttp_status\x12!.google.protobuf.EnumValueOptions\x18\xa1\x90\x05 \x01(\x05R\n" +
	"httpStatus:H\n" +
	"\rerror_message\x12!.google.protobuf.EnumValueOptions\x18\xa2\x90\x05 \x01(\tR\ferrorMessageB/Z-github.com/fztcjjl/quix/proto/errdesc;errdescb\x06proto3"

var file_errdesc_errdesc_proto_goTypes = []any{
	(*descriptorpb.EnumValueOptions)(nil), // 0: google.protobuf.EnumValueOptions
}
var file_errdesc_errdesc_proto_depIdxs = []int32{
	0, // 0: errdesc.http_status:extendee -> google.protobuf.EnumValueOptions
	0, // 1: errdesc.error_message:extendee -> google.protobuf.EnumValueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errdesc_errdesc_proto_init() }
func file_errdesc_errdesc_proto_init() {
	if File_errdesc_errdesc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errdesc_errdesc_proto_rawDesc), len(file_errdesc_errdesc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_errdesc_errdesc_proto_goTypes,
		DependencyIndexes: file_errdesc_errdesc_proto_depIdxs,
		ExtensionInfos:    file_errdesc_errdesc_proto_extTypes,
	}.Build()
	File_errdesc_errdesc_proto = out.File
	file_errdesc_errdesc_proto_goTypes = nil
	file_errdesc_errdesc_proto_depIdxs = nil
}
